web_socket: true

cert_file: auth/.cert.pem
key_file: auth/.privkey.pem

protection:
  csrf_token: true
  max_request: 5
  ban_time: 30m

upload:
  max: 1k
reverse_proxy:
  enabled: false
  addrs: localhost


